version: 0.2

phases:
  install:
    commands:
      - echo "Installing prerequisites..."
      - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - curl -Lo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli.zip -d /opt/
      - ln -s /opt/sonar-scanner-*/bin/sonar-scanner /usr/local/bin/sonar-scanner
      - echo "Tools installed successfully."

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo "Setting environment variables..."
      - TAG="latest"
      - export SONAR_HOST_URL=$SONARQUBE_HOST
      - export SONAR_TOKEN=$SONARQUBE_TOKEN
      - export EKS_CLUSTER_NAME=$EKS_CLUSTER
      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAG
      - echo "Environment variables set."

  build:
    commands:
      - echo "Running SonarQube scan..."
      - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.sources=./web -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
      - echo "Building Docker image..."
      - docker build -f web/public/Dockerfile --tag $IMAGE_URI .
      - echo "Running Trivy scan..."
      - trivy image --format table --output trivy-report.txt $IMAGE_URI
      - trivy image --format json --output trivy-report.json $IMAGE_URI

artifacts:
  files:
    - trivy-report.txt
    - trivy-report.json